version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing ..."
      # - npm install -g @angular/cli@17
      - npm install 
  build:
    commands:
      - npx ng build
artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'
