version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Sử dụng Node.js phiên bản tương thích
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the Angular application...
      - npm run build -- --configuration=production

artifacts:
  files:
    - '**/*'
  base-directory: dist/my-angular-project # Thư mục output từ angular.json
